"""Add _lesson_order on Course

Revision ID: 8aa739deac37
Revises: a77443931168
Create Date: 2021-01-21 08:56:38.751879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa739deac37'
down_revision = 'a77443931168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('_lesson_order', sa.ARRAY(sa.Integer()), nullable=True))
    op.create_unique_constraint(None, 'course', ['id'])
    op.create_unique_constraint(None, 'lesson', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_vocab_progress', ['id'])
    op.create_unique_constraint(None, 'vocab', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vocab', type_='unique')
    op.drop_constraint(None, 'user_vocab_progress', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'lesson', type_='unique')
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_column('course', '_lesson_order')
    # ### end Alembic commands ###
