version: "3.9"

services:
  api:
    container_name: api
    build: ./api/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
        - db
  
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: "jargon"
      POSTGRES_PASSWORD: "root"

  frontend:
    container_name: frontend
    build: ./frontend/
    volumes:
      - ./frontend:/frontend
      - '/frontend/node_modules'
    ports:
      - "80:80"
    command: npm run serve -- --port 80