version: "3.9"

services:
  api:
    build: ./api/
    environment:
      APP_NAME: ${APP_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      API_SECRET_KEY: ${API_SECRET_KEY}
      API_SECURITY_PASSWORD_SALT: ${API_SECURITY_PASSWORD_SALT}
      API_DOMAIN: ${API_DOMAIN}
      API_PORT: ${API_PORT}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/api
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db

  db:
    container_name: ${POSTGRES_HOST}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    expose:
      - $POSTGRES_PORT
    command: -p ${POSTGRES_PORT}
    ports:
      - $POSTGRES_PORT
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build: ./frontend/
    volumes:
      - ./frontend:/frontend
      - "/frontend/node_modules"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      VUE_APP_APP_NAME: ${APP_NAME}
      VUE_APP_API_DOMAIN: ${API_DOMAIN}
      VUE_APP_API_PORT: ${API_PORT}
      VUE_APP_API_VERSION: ${API_VERSION}
      VUE_APP_FRONTEND_PORT: ${FRONTEND_PORT}
    logging:
      driver: none
    command: npm run serve -- --port ${FRONTEND_PORT}
