version: "3.9"

services:
  api:
    build: ./api/
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
        - db
  
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    expose: 
      - $POSTGRES_PORT
    command: -p $POSTGRES_PORT
    ports:
      - $POSTGRES_PORT

  frontend:
    container_name: frontend
    build: ./frontend/
    volumes:
      - ./frontend:/frontend
      - '/frontend/node_modules'
    ports:
      - "80:80"
    command: npm run serve -- --port 80