version: "3.9"

services:
  api:
    env_file:
      - ".env"
    build: ./api/
    environment: 
      POSTGRES_USER: {$POSTGRES_USER}
      POSTGRES_PASSWORD: {$POSTGRES_PASSWORD}

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
        - db
  
  db:
    env_file:
      - ".env"   
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: {$POSTGRES_USER}
      POSTGRES_PASSWORD: {$POSTGRES_PASSWORD}
      POSTGRES_PORT: {$POSTGRES_PORT}
  frontend:
    container_name: frontend
    build: ./frontend/
    volumes:
      - ./frontend:/frontend
      - '/frontend/node_modules'
    ports:
      - "80:$POSTGRES_PORT"
    command: npm run serve -- --port 80